# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Boulder AWS User Group
email: organizers@bawsug.org
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Boulder AWS User Group! We're an inclusive community that brings together 
  anyone interested in cloud computing and AWS technologies. Whether you're a seasoned cloud 
  developer, infrastructure engineer, DevOps professional, student exploring tech careers, 
  or hobbyist tinkering with AWS in your spare time - you belong here. Our group welcomes 
  all skill levels and backgrounds, fostering learning, networking, and knowledge sharing 
  in a supportive environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bawsug.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO and social media
tagline: "Boulder's Premier AWS Community"
keywords: "AWS, cloud computing, Boulder, Denver, user group, meetup, DevOps, serverless, containers"
lang: en_US
timezone: America/Denver
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO Configuration
logo: /assets/icons/bawsug.png
social:
  name: Boulder AWS User Group
  links:
    - https://www.meetup.com/boulder-aws-users-group/
    - https://www.linkedin.com/company/boulder-aws-user-group/

# Organization details for SEO
author:
  name: Boulder AWS User Group
  url: https://bawsug.github.io

# Default SEO settings
defaults:
  - scope:
      path: ""
    values:
      image: /assets/icons/bawsug.png
      author: Boulder AWS User Group

linkedin: https://www.linkedin.com/groups/15184031
logo: /assets/icons/bawsug.png
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
favicon: /assets/icons/bawsug.png
